/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

(* src = "example.v:1.1-3.10" *)
module example(a, b, y);
  (* src = "example.v:1.22-1.23" *)
  input a;
  wire a;
  (* src = "example.v:1.25-1.26" *)
  input b;
  wire b;
  (* src = "example.v:1.35-1.36" *)
  output y;
  wire y;
  assign y = b & a;
endmodule
